/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomeFavorite: typeof import('./src/components/home/HomeFavorite.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeNavbar: typeof import('./src/components/home/HomeNavbar.vue')['default']
    HomeProfile: typeof import('./src/components/home/HomeProfile.vue')['default']
    HomeResource: typeof import('./src/components/home/HomeResource.vue')['default']
    HomeReward: typeof import('./src/components/home/HomeReward.vue')['default']
    HomeSidebar: typeof import('./src/components/home/HomeSidebar.vue')['default']
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsCurrencyExchangeRounded: typeof import('~icons/material-symbols/currency-exchange-rounded')['default']
    IMaterialSymbolsFormatListBulleted: typeof import('~icons/material-symbols/format-list-bulleted')['default']
    IMaterialSymbolsSearch: typeof import('~icons/material-symbols/search')['default']
    IMdiCardsHeartOutline: typeof import('~icons/mdi/cards-heart-outline')['default']
    IMdiMessageProcessingOutline: typeof import('~icons/mdi/message-processing-outline')['default']
    IPajamasProfile: typeof import('~icons/pajamas/profile')['default']
    MainSearch: typeof import('./src/components/single/MainSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/utils/SearchBar.vue')['default']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarTooltip: typeof import('@varlet/ui')['_TooltipComponent']
  }
}
