/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomeFavorite: typeof import('./src/components/home/HomeFavorite.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeMessage: typeof import('./src/components/home/HomeMessage.vue')['default']
    HomeNavbar: typeof import('./src/components/home/HomeNavbar.vue')['default']
    HomeNavBar: typeof import('./src/components/home/HomeNavBar.vue')['default']
    HomeProfile: typeof import('./src/components/home/HomeProfile.vue')['default']
    HomeResource: typeof import('./src/components/home/HomeResource.vue')['default']
    HomeReward: typeof import('./src/components/home/HomeReward.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/utils/SearchBar.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
}
