/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UserContract } from "./UserContract";
export * as factories from "./factories";
export { UserContract__factory } from "./factories/UserContract__factory";
