/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ImplementationInterfaceContract
  extends Truffle.Contract<ImplementationInterfaceInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<ImplementationInterfaceInstance>;
}

type AllEvents = never;

export interface ImplementationInterfaceInstance
  extends Truffle.ContractInstance {
  addCategory: {
    (name: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(name: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      name: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      name: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addFileComment: {
    (
      file_address: string,
      content: string,
      images: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      file_address: string,
      content: string,
      images: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      file_address: string,
      content: string,
      images: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      file_address: string,
      content: string,
      images: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addFileSubComment: {
    (
      file_address: string,
      target_address: string,
      comment_address: string,
      content: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      file_address: string,
      target_address: string,
      comment_address: string,
      content: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      file_address: string,
      target_address: string,
      comment_address: string,
      content: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      file_address: string,
      target_address: string,
      comment_address: string,
      content: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getCategorySlice(
    cursor: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: { category_address: string; name: string; num: BN }[];
    1: string;
    2: boolean;
  }>;

  getFileBriefInfos(
    cursor: string,
    category_address: string,
    order: number | BN | string,
    reverse: boolean,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: {
      file_address: string;
      category_address: string;
      is_buy: boolean;
      name: string;
      title: string;
      owner: string;
      description: string;
      cover: string;
      price: BN;
      up_num: BN;
      down_num: BN;
      buyer_num: BN;
      comment_num: BN;
      up_and_down: BN;
      upload_timestamp: BN;
    }[];
    1: string;
    2: boolean;
  }>;

  getFileChildrenComments(
    file_address: string,
    comment_address: string,
    cursor: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: {
      target_address: string;
      comment_address: string;
      sub_comment_address: string;
      content: string;
      author: {
        user_address: string;
        avatar: string;
        nickname: string;
        experience: BN;
      };
      target_author: {
        user_address: string;
        avatar: string;
        nickname: string;
        experience: BN;
      };
      up_num: BN;
      down_num: BN;
      up_and_down: BN;
      comment_timestamp: BN;
    }[];
    1: string;
    2: boolean;
  }>;

  getFileDetailInfo(
    file_address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    owner: string;
    file_address: string;
    category_address: string;
    is_buy: boolean;
    name: string;
    title: string;
    description: string;
    ipfs_address: string;
    images: string[];
    price: BN;
    up_num: BN;
    down_num: BN;
    buyer_num: BN;
    comment_num: BN;
    up_and_down: BN;
    upload_timestamp: BN;
  }>;

  getFileRootComments(
    file_address: string,
    cursor: string,
    order: number | BN | string,
    reverse: boolean,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: {
      comment_address: string;
      children_comments: {
        target_address: string;
        comment_address: string;
        sub_comment_address: string;
        content: string;
        author: {
          user_address: string;
          avatar: string;
          nickname: string;
          experience: BN;
        };
        target_author: {
          user_address: string;
          avatar: string;
          nickname: string;
          experience: BN;
        };
        up_num: BN;
        down_num: BN;
        up_and_down: BN;
        comment_timestamp: BN;
      }[];
      content: string;
      images: string[];
      author: {
        user_address: string;
        avatar: string;
        nickname: string;
        experience: BN;
      };
      up_num: BN;
      down_num: BN;
      up_and_down: BN;
      comment_num: BN;
      comment_timestamp: BN;
    }[];
    1: string;
    2: boolean;
  }>;

  getOtherSimpleInfo(
    user_address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    major: string;
    avatar: string;
    nickname: string;
    signature: string;
    heart: BN;
    medal_num: BN;
    experience: BN;
    follower_num: BN;
    uploaded_file_num: BN;
  }>;

  getSelfFileBriefInfos(
    cursor: string,
    reverse: boolean,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: {
      file_address: string;
      category_address: string;
      is_buy: boolean;
      name: string;
      title: string;
      owner: string;
      description: string;
      cover: string;
      price: BN;
      up_num: BN;
      down_num: BN;
      buyer_num: BN;
      comment_num: BN;
      up_and_down: BN;
      upload_timestamp: BN;
    }[];
    1: string;
    2: boolean;
  }>;

  getSelfInfo(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    major: string;
    avatar: string;
    nickname: string;
    signature: string;
    ID: BN;
    coins: BN;
    heart: BN;
    experience: BN;
    follower_num: BN;
    following_num: BN;
    login_timestamp: BN;
    uploaded_file_num: BN;
  }>;

  isRegistered(
    user_address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  register: {
    (nickname: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  renounceAdmin: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  transferAdmin: {
    (new_admin: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      new_admin: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      new_admin: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      new_admin: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  upAndDownFile: {
    (
      file_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      file_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      file_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      file_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  upAndDownFileComment: {
    (
      file_address: string,
      comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      file_address: string,
      comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      file_address: string,
      comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      file_address: string,
      comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  upAndDownFileSubComment: {
    (
      file_address: string,
      comment_address: string,
      sub_comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      file_address: string,
      comment_address: string,
      sub_comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      file_address: string,
      comment_address: string,
      sub_comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      file_address: string,
      comment_address: string,
      sub_comment_address: string,
      is_up: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateAvatar: {
    (avatar: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(avatar: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      avatar: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      avatar: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateNickname: {
    (nickname: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateSignature: {
    (signature: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      signature: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      signature: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      signature: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  uploadFile: {
    (
      ipfs_address: string,
      name: string,
      title: string,
      description: string,
      category_address: string,
      images: string[],
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      ipfs_address: string,
      name: string,
      title: string,
      description: string,
      category_address: string,
      images: string[],
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      ipfs_address: string,
      name: string,
      title: string,
      description: string,
      category_address: string,
      images: string[],
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      ipfs_address: string,
      name: string,
      title: string,
      description: string,
      category_address: string,
      images: string[],
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  init: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  methods: {
    addCategory: {
      (name: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(name: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(
        name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addFileComment: {
      (
        file_address: string,
        content: string,
        images: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        file_address: string,
        content: string,
        images: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        file_address: string,
        content: string,
        images: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        file_address: string,
        content: string,
        images: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addFileSubComment: {
      (
        file_address: string,
        target_address: string,
        comment_address: string,
        content: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        file_address: string,
        target_address: string,
        comment_address: string,
        content: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        file_address: string,
        target_address: string,
        comment_address: string,
        content: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        file_address: string,
        target_address: string,
        comment_address: string,
        content: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getCategorySlice(
      cursor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: { category_address: string; name: string; num: BN }[];
      1: string;
      2: boolean;
    }>;

    getFileBriefInfos(
      cursor: string,
      category_address: string,
      order: number | BN | string,
      reverse: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: {
        file_address: string;
        category_address: string;
        is_buy: boolean;
        name: string;
        title: string;
        owner: string;
        description: string;
        cover: string;
        price: BN;
        up_num: BN;
        down_num: BN;
        buyer_num: BN;
        comment_num: BN;
        up_and_down: BN;
        upload_timestamp: BN;
      }[];
      1: string;
      2: boolean;
    }>;

    getFileChildrenComments(
      file_address: string,
      comment_address: string,
      cursor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: {
        target_address: string;
        comment_address: string;
        sub_comment_address: string;
        content: string;
        author: {
          user_address: string;
          avatar: string;
          nickname: string;
          experience: BN;
        };
        target_author: {
          user_address: string;
          avatar: string;
          nickname: string;
          experience: BN;
        };
        up_num: BN;
        down_num: BN;
        up_and_down: BN;
        comment_timestamp: BN;
      }[];
      1: string;
      2: boolean;
    }>;

    getFileDetailInfo(
      file_address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      owner: string;
      file_address: string;
      category_address: string;
      is_buy: boolean;
      name: string;
      title: string;
      description: string;
      ipfs_address: string;
      images: string[];
      price: BN;
      up_num: BN;
      down_num: BN;
      buyer_num: BN;
      comment_num: BN;
      up_and_down: BN;
      upload_timestamp: BN;
    }>;

    getFileRootComments(
      file_address: string,
      cursor: string,
      order: number | BN | string,
      reverse: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: {
        comment_address: string;
        children_comments: {
          target_address: string;
          comment_address: string;
          sub_comment_address: string;
          content: string;
          author: {
            user_address: string;
            avatar: string;
            nickname: string;
            experience: BN;
          };
          target_author: {
            user_address: string;
            avatar: string;
            nickname: string;
            experience: BN;
          };
          up_num: BN;
          down_num: BN;
          up_and_down: BN;
          comment_timestamp: BN;
        }[];
        content: string;
        images: string[];
        author: {
          user_address: string;
          avatar: string;
          nickname: string;
          experience: BN;
        };
        up_num: BN;
        down_num: BN;
        up_and_down: BN;
        comment_num: BN;
        comment_timestamp: BN;
      }[];
      1: string;
      2: boolean;
    }>;

    getOtherSimpleInfo(
      user_address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      major: string;
      avatar: string;
      nickname: string;
      signature: string;
      heart: BN;
      medal_num: BN;
      experience: BN;
      follower_num: BN;
      uploaded_file_num: BN;
    }>;

    getSelfFileBriefInfos(
      cursor: string,
      reverse: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: {
        file_address: string;
        category_address: string;
        is_buy: boolean;
        name: string;
        title: string;
        owner: string;
        description: string;
        cover: string;
        price: BN;
        up_num: BN;
        down_num: BN;
        buyer_num: BN;
        comment_num: BN;
        up_and_down: BN;
        upload_timestamp: BN;
      }[];
      1: string;
      2: boolean;
    }>;

    getSelfInfo(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      major: string;
      avatar: string;
      nickname: string;
      signature: string;
      ID: BN;
      coins: BN;
      heart: BN;
      experience: BN;
      follower_num: BN;
      following_num: BN;
      login_timestamp: BN;
      uploaded_file_num: BN;
    }>;

    isRegistered(
      user_address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    register: {
      (nickname: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    renounceAdmin: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    transferAdmin: {
      (new_admin: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        new_admin: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        new_admin: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        new_admin: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    upAndDownFile: {
      (
        file_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        file_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        file_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        file_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    upAndDownFileComment: {
      (
        file_address: string,
        comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        file_address: string,
        comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        file_address: string,
        comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        file_address: string,
        comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    upAndDownFileSubComment: {
      (
        file_address: string,
        comment_address: string,
        sub_comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        file_address: string,
        comment_address: string,
        sub_comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        file_address: string,
        comment_address: string,
        sub_comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        file_address: string,
        comment_address: string,
        sub_comment_address: string,
        is_up: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateAvatar: {
      (avatar: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        avatar: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        avatar: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        avatar: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateNickname: {
      (nickname: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateSignature: {
      (signature: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        signature: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        signature: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        signature: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    uploadFile: {
      (
        ipfs_address: string,
        name: string,
        title: string,
        description: string,
        category_address: string,
        images: string[],
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        ipfs_address: string,
        name: string,
        title: string,
        description: string,
        category_address: string,
        images: string[],
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        ipfs_address: string,
        name: string,
        title: string,
        description: string,
        category_address: string,
        images: string[],
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        ipfs_address: string,
        name: string,
        title: string,
        description: string,
        category_address: string,
        images: string[],
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    init: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
