/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface UserContractContract
  extends Truffle.Contract<UserContractInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<UserContractInstance>;
}

type AllEvents = never;

export interface UserContractInstance extends Truffle.ContractInstance {
  admin(txDetails?: Truffle.TransactionDetails): Promise<string>;

  register: {
    (nickname: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      avatar: string;
      nickname: string;
      signature: string;
      login_timestamp: BN;
      following_num: BN;
      follower_num: BN;
      ID: BN;
      major: string;
      heart: BN;
    }>;
    sendTransaction(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      nickname: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  isRegistered(
    user_address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  getSelfInfo(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    avatar: string;
    nickname: string;
    signature: string;
    login_timestamp: BN;
    following_num: BN;
    follower_num: BN;
    ID: BN;
    major: string;
    heart: BN;
  }>;

  getUserInfo(
    user_address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    avatar: string;
    nickname: string;
    signature: string;
    login_timestamp: BN;
    following_num: BN;
    follower_num: BN;
    heart: BN;
  }>;

  getFollowings(
    cursor: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: { avatar: string; nickname: string }[]; 1: BN }>;

  getFollowers(
    cursor: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: { avatar: string; nickname: string }[]; 1: BN }>;

  setFollow: {
    (
      target_user: string,
      is_follow: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      target_user: string,
      is_follow: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      target_user: string,
      is_follow: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      target_user: string,
      is_follow: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    admin(txDetails?: Truffle.TransactionDetails): Promise<string>;

    register: {
      (nickname: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{
        avatar: string;
        nickname: string;
        signature: string;
        login_timestamp: BN;
        following_num: BN;
        follower_num: BN;
        ID: BN;
        major: string;
        heart: BN;
      }>;
      sendTransaction(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        nickname: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    isRegistered(
      user_address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    getSelfInfo(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      avatar: string;
      nickname: string;
      signature: string;
      login_timestamp: BN;
      following_num: BN;
      follower_num: BN;
      ID: BN;
      major: string;
      heart: BN;
    }>;

    getUserInfo(
      user_address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      avatar: string;
      nickname: string;
      signature: string;
      login_timestamp: BN;
      following_num: BN;
      follower_num: BN;
      heart: BN;
    }>;

    getFollowings(
      cursor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: { avatar: string; nickname: string }[]; 1: BN }>;

    getFollowers(
      cursor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: { avatar: string; nickname: string }[]; 1: BN }>;

    setFollow: {
      (
        target_user: string,
        is_follow: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        target_user: string,
        is_follow: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        target_user: string,
        is_follow: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        target_user: string,
        is_follow: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
